# Generated by Django 4.2.9 on 2024-02-12 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Outpatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_outpatient",
                    models.BooleanField(default=False, verbose_name="外来対応医療機関"),
                ),
                (
                    "is_positive_patients",
                    models.BooleanField(
                        default=False, verbose_name="陽性者の治療に関与する医療機関"
                    ),
                ),
                (
                    "public_health_care_center",
                    models.TextField(blank=True, null=True, verbose_name="保健所"),
                ),
                (
                    "medical_institution_name",
                    models.CharField(max_length=256, verbose_name="医療機関名"),
                ),
                (
                    "city",
                    models.TextField(blank=True, null=True, verbose_name="市町村"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="住所"),
                ),
                (
                    "phone_number",
                    models.TextField(blank=True, null=True, verbose_name="電話番号"),
                ),
                (
                    "is_target_not_family",
                    models.BooleanField(verbose_name="かかりつけ患者以外の診療"),
                ),
                ("is_pediatrics", models.BooleanField(verbose_name="小児対応の可否")),
                ("mon", models.TextField(blank=True, null=True, verbose_name="月")),
                ("tue", models.TextField(blank=True, null=True, verbose_name="火")),
                ("wed", models.TextField(blank=True, null=True, verbose_name="水")),
                ("thu", models.TextField(blank=True, null=True, verbose_name="木")),
                ("fri", models.TextField(blank=True, null=True, verbose_name="金")),
                ("sat", models.TextField(blank=True, null=True, verbose_name="土")),
                ("sun", models.TextField(blank=True, null=True, verbose_name="日")),
                (
                    "is_face_to_face_for_positive_patients",
                    models.BooleanField(default=False, verbose_name="外来対応"),
                ),
                (
                    "is_online_for_positive_patients",
                    models.BooleanField(default=False, verbose_name="オンライン診療"),
                ),
                (
                    "is_home_visitation_for_positive_patients",
                    models.BooleanField(default=False, verbose_name="訪問診療"),
                ),
                (
                    "memo",
                    models.BooleanField(blank=True, null=True, verbose_name="備考"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
        ),
    ]
