# Generated by Django 4.2.9 on 2024-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpatients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outpatient",
            name="is_pediatrics",
            field=models.BooleanField(default=False, verbose_name="小児対応の可否"),
        ),
        migrations.AlterField(
            model_name="outpatient",
            name="is_target_not_family",
            field=models.BooleanField(
                default=False, verbose_name="かかりつけ患者以外の診療"
            ),
        ),
    ]
