# Generated by Django 4.2.9 on 2024-02-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpatients", "0003_rename_create_by_outpatient_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outpatient",
            name="memo",
            field=models.TextField(blank=True, null=True, verbose_name="備考"),
        ),
    ]
