# Generated by Django 4.2.9 on 2024-03-31 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("outpatients", "0004_alter_outpatient_memo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_institution_name",
                    models.CharField(max_length=256, verbose_name="医療機関名"),
                ),
                ("latitude", models.FloatField(default=0, verbose_name="緯度")),
                ("longitude", models.FloatField(default=0, verbose_name="経度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
        ),
    ]
